# Generated by Django 4.1 on 2022-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='region_name',
            field=models.CharField(max_length=230),
        ),
    ]
