# Generated by Django 4.1 on 2022-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
